# Configuration for Exiobase Trade Flow Analysis
# This file controls which type of trade flow analysis to run

# Trade flow type: 'imports', 'exports', or 'domestic'
TRADEFLOW: 'imports'

# Analysis year
YEAR: 2019

# Country for analysis
COUNTRY: 'US'

# Output folder structure
FOLDERS:
  base: 'csv'
  imports: 'csv/US/imports'
  exports: 'csv/US/exports' 
  domestic: 'csv/US/domestic'

# File naming patterns
FILES:
  # Core trade files
  industry_tradeflow: 'industry_tradeflow.csv'
  trade_factors: 'trade_factors_lite.csv'
  trade_impacts: 'trade_impacts.csv'
  
  # Split resource files
  trade_employment: 'trade_employment.csv'
  trade_resources: 'trade_resources.csv'  # includes crops
  trade_materials: 'trade_materials.csv'
  
  # Reference files (always in base folder)
  industries: 'industries.csv'
  factors: 'factors.csv'

# Processing settings
PROCESSING:
  # For imports: region1 != COUNTRY, region2 == COUNTRY
  # For exports: region1 == COUNTRY, region2 != COUNTRY  
  # For domestic: region1 == COUNTRY, region2 == COUNTRY
  sample_size: 1000  # Number of trade flows to process for performance
  min_impact_threshold: 0.001  # Minimum impact value to include